#!/bin/bash

# Generate single file header. Called from makefile. 

source="jsontool.h"
target="../dist/jsontool.h"

echo "// This file is automatically generated; do not edit.\n" > $target

while read line; do

	path="$(echo "$line" | egrep "\s*#include\s+\"" | sed "s/#include\s*\"\(.*\)\"/\1/")"

	if [ "$path" = "" ]; then
	
		echo "$line" >> "$target"
	
	else
	
		echo "$(cat "$path")" >> "$target"
	
	fi

done < "$source"
